CREATE TABLE IF NOT EXISTS sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    target_url TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    poll_interval_minutes INTEGER NOT NULL,
    next_poll_at TIMESTAMPTZ NOT NULL,
    initial_backfill_done BOOLEAN NOT NULL,
    backfill_completed_at TIMESTAMPTZ,
    last_polled_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    last_error_at TIMESTAMPTZ,
    last_error_message TEXT,
    consecutive_failures INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS source_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    canonical_url TEXT NOT NULL,
    title TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    body_text TEXT,
    fetch_status VARCHAR(20) NOT NULL,
    fetch_retry_count INTEGER NOT NULL,
    fetch_error_message TEXT,
    wiki_status VARCHAR(20) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT source_documents_source_id_canonical_url_key UNIQUE (
        source_id,
        canonical_url
    )
);

CREATE TABLE IF NOT EXISTS ingestion_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_document_id BIGINT NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL,
    error_message TEXT,
    queued_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT ingestion_jobs_source_document_id_key UNIQUE (source_document_id)
);

CREATE INDEX IF NOT EXISTS idx_sources_due_poll
ON sources (enabled, next_poll_at);

CREATE INDEX IF NOT EXISTS idx_source_documents_source
ON source_documents (source_id, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_source_documents_wiki_status
ON source_documents (wiki_status);

CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_status
ON ingestion_jobs (status, queued_at);

CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_source_document
ON ingestion_jobs (source_document_id);
